/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardCompanyIdRouteImport } from './routes/dashboard/$companyId'
import { Route as ExperiencesExperienceIdRouteImport } from './routes/experiences/$experienceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompanyIdRoute = DashboardCompanyIdRouteImport.update({
  id: '/dashboard/$companyId',
  path: '/dashboard/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesExperienceIdRoute = ExperiencesExperienceIdRouteImport.update({
  id: '/experiences/$experienceId',
  path: '/experiences/$experienceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/$companyId': typeof DashboardCompanyIdRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$companyId': typeof DashboardCompanyIdRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/$companyId': typeof DashboardCompanyIdRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard/$companyId' | '/experiences/$experienceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard/$companyId' | '/experiences/$experienceId'
  id: '__root__' | '/' | '/dashboard/$companyId' | '/experiences/$experienceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardCompanyIdRoute: typeof DashboardCompanyIdRoute
  ExperiencesExperienceIdRoute: typeof ExperiencesExperienceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$companyId': {
      id: '/dashboard/$companyId'
      path: '/dashboard/$companyId'
      fullPath: '/dashboard/$companyId'
      preLoaderRoute: typeof DashboardCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$experienceId': {
      id: '/experiences/$experienceId'
      path: '/experiences/$experienceId'
      fullPath: '/experiences/$experienceId'
      preLoaderRoute: typeof ExperiencesExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardCompanyIdRoute: DashboardCompanyIdRoute,
  ExperiencesExperienceIdRoute: ExperiencesExperienceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
